---
services:
  cwa:
    image: crocodilestick/calibre-web-automated:latest
    environment:
      # Only change these if you know what you're doing
      - PUID=1000
      - PGID=1000
      # Edit to match your current timezone https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Asia/Tokyo
      # Hardcover API Key required for Hardcover as a Metadata Provider, get one here: https://docs.hardcover.app/api/getting-started/
      - HARDCOVER_TOKEN=your_hardcover_api_key_here
      # If your library is on a network share (e.g., NFS/SMB), disables WAL and chown to reduce locking/permission issues,
      # and switches file watching to polling (more reliable on network mounts) instead of inotify.
      # Accepts: true/false (default: false)
      - NETWORK_SHARE_MODE=false
      # If you want to force polling mode regardless of share type, set CWA_WATCH_MODE=poll
      # - CWA_WATCH_MODE=poll
      # Skip the automatic library detection/mount at startup. When enabled, the auto-library service will not run.
      # Accepts: true/yes/1 to disable auto-mount (default: false)
      - DISABLE_LIBRARY_AUTOMOUNT=true
    volumes:
      # CW users migrating should stop their existing CW instance, make a copy of the config folder, and bind that here to carry over all of their user settings etc.
      - ./config:/config
      # This is an ingest dir, NOT a library one. Anything added here will be automatically added to your library according to the settings you have configured in CWA Settings page. All files placed here are REMOVED AFTER PROCESSING
      - ./cwa-book-ingest:/cwa-book-ingest
      # If you don't have an existing library, CWA will automatically create one at the bind provided here
      - ./calibre-library:/calibre-library
      # If you use calibre plugins, you can bind your plugins folder here to have CWA attempt to add them to it's workflow (WIP)
      # If you are starting with a fresh install, you also need to copy plugins\..\customize.py.json to the corresponding docker location (the config path above + .config/calibre/customize.py.json)
      # - /path/to/your/calibre/plugins/folder:/config/.config/calibre/plugins
    ports:
      # Change the first number to change the port you want to access the Web UI, not the second
      - 8083:8083
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    depends_on:
      - cwa
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    restart: always
