version: '3.8'

services:
  registry:
    image: registry:latest
    container_name: registry
    restart: always
    hostname: registry
    ports:
      - '5000:5000'
    volumes:
      - './registry:/var/lib/registry'
  registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry-frontend
    restart: always
    hostname: registry-frontend
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
    ports:
      - 8080:80
    volumes:
      - ./scripts:/scripts
    command: /scripts/issue-159-workaround.sh
