name: dev-arch build

on:
  push:
    branches: ["master"]
    paths:
      - "dev-arch/**"
      - ".github/**"
  schedule:
    - cron: 0 0 1 * *

jobs:
  build-and-deploy:
    strategy:
      matrix:
        include:
          - tag: base
            args: ""
          - tag: c
            args: ENABLE_C=true
          - tag: node
            args: ENABLE_NODE=true
          - tag: python
            args: ENABLE_PYTHON=true
          - tag: rust
            args: ENABLE_RUST=true
          - tag: all
            args: |
              ENABLE_C=true
              ENABLE_NODE=true
              ENABLE_PYTHON=true
              ENABLE_RUST=true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: ./dev-arch
          push: true
          build-args: ${{ matrix.args }}
          tags: ghcr.io/${{ github.repository_owner }}/dev-arch:${{ matrix.tag }}
